### ISSUE TITLE
go get github.com/henrylee2cn/pholcus 的时候报错了

### ISSUE THREAD

**Issue by WhV5** [andeya/pholcus#112]
# github.com/henrylee2cn/pholcus
C:\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
c:/mingw/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `C:\Users\henry\AppData\Local\Temp\go-link-908393803\000000.o' is incompatible with i386:x86-64 output
collect2.exe: error: ld returned 1 exit status

这个是报错的文本信息，请问这个是什么错误呢

**Comment by flinus552** [comment]
go install -ldflags="-H windowsgui"

**Comment by vulcangz** [comment]
Maybe you can try:
```
λ go install -ldflags "-linkmode=internal"
```

**Comment by presoulgo** [comment]
same error

**Comment by andeya** [comment]
gcc 版本和go不批的问题，解决办法：
1. 移除GUI
2. 尝试其他gcc版本

**Comment by chenxun450** [comment]
> Maybe you can try:
> 
> ```
> λ go install -ldflags "-linkmode=internal"
> ```



> Maybe you can try:
> 
> ```
> λ go install -ldflags "-linkmode=internal"
> ```
用这个可行。我的gcc是msys2中的 9.2版本
