### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by winterswang** [andeya/pholcus#113]
go install
# github.com/henrylee2cn/pholcus
/usr/local/go/pkg/tool/darwin_amd64/link: /usr/local/go/pkg/tool/darwin_amd64/link: combining dwarf failed: Unknown load command 0x32 (50)

遇到了这种错误
我的golang版本
go version go1.10.3 darwin/amd64

**Comment by andeya** [comment]
mac不支持gui的，是不是因为指定了gui版本？
