### ISSUE TITLE
请问 /web/pholcus-web.go 中 appInit() 中app.SetLog(Lsc).SetAppConf() 中的Lsc 是什么呢？

### ISSUE THREAD

**Issue by lueliCMU** [andeya/pholcus#122]
您好， 首先谢谢您提供代码。我在学习您的代码过程中，发现了一个小疑问：在/web/pholcus-web.go中， 函数appInit() 中app.SetLog(Lsc).SetAppConf() 中的Lsc。 Lsc的类型应该是io.writer。但是我没有看到它的定义。请问能稍微解答一下吗？谢谢 ！

**Comment by andeya** [comment]
Lsc是 *LogSocketController，它满足 io.Writer 接口。go接口是 duck typing 设计

**Comment by lueliCMU** [comment]
谢谢！ 明白了！
