### ISSUE TITLE
执行 go get -u -v github.com/henrylee2cn/pholcus 失败

### ISSUE THREAD

**Issue by beyond-infra** [andeya/pholcus#123]
# github.com/henrylee2cn/pholcus/app/distribute
../../go/pkg/mod/github.com/henrylee2cn/pholcus@v1.3.4/app/distribute/master_api.go:6:2: imported and not used: "github.com/henrylee2cn/teleport" as tp
../../go/pkg/mod/github.com/henrylee2cn/pholcus@v1.3.4/app/distribute/master_api.go:10:31: undefined: teleport
../../go/pkg/mod/github.com/henrylee2cn/pholcus@v1.3.4/app/distribute/master_api.go:11:9: undefined: teleport
../../go/pkg/mod/github.com/henrylee2cn/pholcus@v1.3.4/app/distribute/master_api.go:25:48: undefined: teleport
../../go/pkg/mod/github.com/henrylee2cn/pholcus@v1.3.4/app/distribute/master_api.go:27:9: undefined: teleport
../../go/pkg/mod/github.com/henrylee2cn/pholcus@v1.3.4/app/distribute/master_api.go:33:42: undefined: teleport
../../go/pkg/mod/github.com/henrylee2cn/pholcus@v1.3.4/app/distribute/slave_api.go:7:2: imported and not used: "github.com/henrylee2cn/teleport" as tp
../../go/pkg/mod/github.com/henrylee2cn/pholcus@v1.3.4/app/distribute/slave_api.go:11:30: undefined: teleport
../../go/pkg/mod/github.com/henrylee2cn/pholcus@v1.3.4/app/distribute/slave_api.go:12:9: undefined: teleport
../../go/pkg/mod/github.com/henrylee2cn/pholcus@v1.3.4/app/distribute/slave_api.go:23:47: undefined: teleport
../../go/pkg/mod/github.com/henrylee2cn/pholcus@v1.3.4/app/distribute/slave_api.go:12:9: too many errors

**Comment by andeya** [comment]
这是 go mod 的 误报，我检查过代码是正确的，也能编译通过

**Comment by gyn7561** [comment]
我也遇到这个问题了，mac/windows 上都抱这个错，go版本 1.14.2

**Comment by antiphy** [comment]
> 这是 go mod 的 误报，我检查过代码是正确的，也能编译通过

@henrylee2cn github.com/henrylee2cn/teleport这个地址现在重定向到erpc了, 但是我从go.pkg上看到teleport的源码里面package声明的package name是tp而不是teleport, 我想是这个原因导致的, 能否修复一下呢？

**Comment by ghost** [comment]
@henrylee2cn 同报错，貌似是楼上说的原因，麻烦看看

**Comment by ghost** [comment]
出现该问题的朋友
估计是都设置了goproxy.io代理
我关了代理
然后手动设置http_proxy就可以了 记得fq

**Comment by teslaluo** [comment]
为啥使用了goproxy后执行 go get -u -v github.com/henrylee2cn/pholcus就失败了呢，不是应该一致的吗？国内很依赖goproxy的呀

**Comment by flymenn** [comment]
go mod edit --replace github.com/henrylee2cn/teleport=github.com/henrylee2cn/teleport@v0.5.1-0.20170813165004-3dd5483d6aa1 可以解决问题。
