### ISSUE TITLE
app\distribute\client_api.go:13: cannot use task2 literal (type *task2) as type func(*teleport.NetData) *teleport.NetData in map value

### ISSUE THREAD

**Issue by skykain** [andeya/pholcus#13]
![qq 20160304121325](https://cloud.githubusercontent.com/assets/6811885/13517857/835dd302-e202-11e5-8949-8289c1b09eea.png)這個是什麼問題？

**Comment by skykain** [comment]
GO version go1.6 windows/amd64

**Comment by andeya** [comment]
你的代码全部更新一下，估计是代码没更新不完全
