### ISSUE TITLE
有在项目中如何使用phantomjs方面的教程吗？

### ISSUE THREAD

**Issue by YaHue** [andeya/pholcus#22]
看到项目是支持 phantomjs的 但是不知道如何使用

**Comment by scbizu** [comment]
`request.go`  Line 109-111 : 

	if self.DownloaderID < SURF_ID || self.DownloaderID > PHANTOM_ID {
		self.DownloaderID = SURF_ID
	}

So ,I guess you just need to swap the value of `SURF_ID` with `PHANTOM_ID`  : )

**Comment by andeya** [comment]
- 在文件`./pholcus_pkg/config.ini`中配置phantomjs执行文件的路径，如
```
phantomjs=pholcus_pkg/phantomjs
```
- 在规则中指定请求的下载内核为`DownloaderID=1`，如
```
request.Request{
    Url:  "http://weibo.com/" + id + "/fans?cfs=600&relate=fans&t=1&f=1&type=&Pl_Official_RelationFans__68_page=1#Pl_Official_RelationFans__68",
    Rule:  "好友列表",
    Header: http.Header{"Cookie": []string{cookie}},
    DownloaderID: 1,
```

**Comment by maskwang** [comment]
请问支持用phantomjs模拟dom操作吗？  比如有些数据是要页面点击才会出来的这种

**Comment by excosy** [comment]
@maskwang 这个你可能需要github.com/benbjohnson/phantomjs
