### ISSUE TITLE
How do U solve the problem about the dynamical JavaScript file ?

### ISSUE THREAD

**Issue by scbizu** [andeya/pholcus#23]
hmmm...  As I  see ,you use `phantomJS` to solve this problem ? But ,you do  not  recommend us to do this , so ,there is any solution  if  I only use the default Golang Client?

**Comment by andeya** [comment]
dynamical JavaScript is the rule， while phantomJS is Downloader.
phantomJS is a simple encapsulation tool， but with lower deficiency. You can use "Request.DownloadID=0" to adopt golang downloader.

**Comment by andeya** [comment]
About dynamical JavaScript, you can see here:
https://github.com/henrylee2cn/pholcus/blob/master/app/spider/parsejs.go

**Comment by scbizu** [comment]
Thanks.
