### ISSUE TITLE
Suggestions for the development of pholcus v2.0?

### ISSUE THREAD

**Issue by andeya** [andeya/pholcus#26]
Welcome to discuss the development of  pholcus v2.0 ...

**Comment by Violam** [comment]
1. 蜘蛛的Panic Root等信息，出错的stack信息都被屏蔽了，对于调试自定义蜘蛛特别不方便。
   有时语法失误，引发了panic都不知道是怎么回事。是否有更简易的自定义蜘蛛测试方法。
2. 我尝试生成了csv，但是csv依赖逗号和引号，非常容易出错，因为网页信息杂乱， 换行、逗号什么的，一点点清洗不干净，容易导致生成的csv读取出错，还不如多加一个文本格式的json。
3. 分布式，分担的只是单个任务，任务颗粒度还是挺粗的。能否直接分担细致到一条网址。
4. 任务的运行进度状态，应该有一个更加直观的界面去监控，方便知道任务完成得怎么样了，有多少剩余网址要解析。只是不停的滚日志，在大量采集时很难看清进度。
5. 还是分布式，客服端采到的数据还是放在客户端程序目录下面？开十个客户端就生成了十份，觉得客户端应该更轻一些，只负责爬行解析，服务端更集中一些。客户端更该像蜘蛛，上百客户端随时增减无压力。
6. 单机模式不过是一个比较特别点的分布式，2.0 不如干脆把单机取消，专心服务中心+客户端分布吧。反正单机开两个程序也是一样的分布式。

**Comment by g457165949** [comment]
现在大部分网站都需要登录后才能拍数据，有其类似于新浪这种，但是对于这种规则限制比较严，稍有不慎就开始封你账号，对于登录一个IP 经常换Cookie 新浪很有可能封掉，有没有可能，分布式的时候让客户端和cookie user agent这种绑定功能，我觉得对于蜘蛛 应该更加可自定化。还有开发时候发现特别难调试。

**Comment by sundy-li** [comment]
现在有个问题是, url做缓存,爬取过的url 不会在爬取了,  我觉得在爬取完毕之后, 应该给个配置是否 清掉history这个目录, 方便下次爬取

**Comment by sundy-li** [comment]
大规模爬虫必须要加入dns缓存,我在线上使用 pholcus的时候, 由于dns没有缓存,导致udp请求dns服务器 太过频繁,严重影响性能

事实上, 爬虫在爬取的过程中很多情况在一个站点内 持续爬取, 所以dns缓存是非常有必要的,参考 https://github.com/viki-org/dnscache/blob/master/dnscache.go

加入一个带锁的map即可, @henrylee2cn 作者可以参考下, 不提mr了~   (mr没有贡献值,泪崩)

**Comment by andeya** [comment]
@sundy-li ok，我会在后续更新中将这一功能加进去

**Comment by andeya** [comment]
<网友建议备忘>
北京-烤鸭：
处理代理池的地方不是很合理啊。ping通不代表代理能用，ping不同也不代表不能用，应该是拿着那代理以及端口去访问类似ip138之类的页面，然后能看到对应的ip就应该算是能用的。而且，目前pholcus服务一起来就从本地文件读，读完了只是判断当时的状态，后续代理不能用了，或者换了代理也不能更新，这个不太好。代理这块最好是能拆分成单独服务的。从其他服务中去取可用的代理列表。
另外，那个队列如果能做成使用其他服务的会不会更好？比如用redis或者xxxmq或者阿里云的消息服务，这样也不用分master\client了。
大家直接往队列里扔任务，然后按照自己的负载从队列里取任务进行操作就好了。
另外就是cookie和代理的绑定了，有些站如果发现client请求总是变ip也会封。。。

**Comment by andeya** [comment]
<网友建议备忘>
［香格里拉］-驴大爷 ：
你可以把基本功能作为主攻，其他的功能，做一个组建功能，然后提供接口让大家扩展这样你的工作量也小，大家的工作量也小。爬虫的需求，要么就是很简单，要么就是很复杂，中间态的比较少。复杂化的功能你完全可以组织成组件。
