### ISSUE TITLE
text_out 文件夹中文名称问题

### ISSUE THREAD

**Issue by zvrr** [andeya/pholcus#30]
你好，
当LANG=zh_CN.UTF-8时，文件名被命名为了中文，这个地方是否可以改成数字。
![image](https://cloud.githubusercontent.com/assets/194304/21558270/1b8cabe2-ce72-11e6-80af-2d543155152b.png)

**Comment by andeya** [comment]
数字的有非法字符：冒号

**Comment by andeya** [comment]
或者改为这种形式：2006-01-02 150405？

**Comment by andeya** [comment]
已经改为这种形式： pholcus_pkg/text_out/2006-01-02 150405/xxxx
