### ISSUE TITLE
怎么实现定时采集

### ISSUE THREAD

**Issue by shijunti19** [andeya/pholcus#37]
怎么实现定时采集

**Comment by andeya** [comment]
可以参考百度新闻RSS采集规则
https://github.com/henrylee2cn/pholcus_lib/blob/master/baidunews/baidunews.go

**Comment by shijunti19** [comment]
@henrylee2cn 为什么不是火车头那种，每天几点开始，间隔几小时、几分、几秒，几点结束，采集肯定是运行在服务器或者windows上，一直不关闭的。希望界面和代码都支持，写个例子

**Comment by jackohy** [comment]
百度新闻定时任务长期运行，时间长了会出现很多CLOSE_WAIT状态，会导致无法继续采集
