### ISSUE TITLE
使用pholcus的疑惑

### ISSUE THREAD

**Issue by 10045125** [andeya/pholcus#4]
1.Pholcus是如何爬虫网页，数据如何提取，提取如何存储到数据库
2.Pholcus数据库配置问题，我使用的是mysql，按照给出的demo，和说明文档，我试着用单机版去跑比如京东搜索iPhone6s，结果却是
![image](https://cloud.githubusercontent.com/assets/2945098/11138042/73970ef0-89f8-11e5-8a87-5729dba8bfe8.png)
啥也没有。
3.比如我有一个需求，很简单，可能很多人和我的想法差不多，就是去爬虫一个网站获取想要塞选的信息，存储到数据库中，Pholcus该如何去做，能给出一个简单的demo么。
4.Pholcus如果是需要去完善一个框架并且更多人一起参与，那么良好的文档和清晰的demo我觉得更为重要。

期待您们的回复，一个热爱Go的开发者！

**Comment by andeya** [comment]
感谢你的提问与建议，demo是有很多的，这个是公共维护的一个规则库https://github.com/pholcus/spider_lib。
关于文档的问题，我会在稳定版之前写出来，由于个人时间有限，不能及时写文档，非常抱歉……如果你有什么技术问题需要交流，也可以加Go 大数据欢迎加入Go 大数据42731170这个群。

**Comment by vgocoder** [comment]
@henrylee2cn  you are so polite～haha
