### ISSUE TITLE
反馈一个bug，日志达到一定条数后会协程会卡死

### ISSUE THREAD

**Issue by teslaluo** [andeya/pholcus#50]
经过长时间的采集图片后，发现到后来内存剧增，并大量goroutine存在，加了一些日志做跟踪，发现协程在输出完文件后，就在日志那里卡住了，导致图片的内存无法释放
1.代码如下，加了些日志：
![ww6lkno7qtvj u23y1 1i2c](https://user-images.githubusercontent.com/3477277/28070365-34be2758-667f-11e7-8bf7-7faa9b3b838d.png)

2.日志如下：
![fk w lm4qm59pbs vgorfy](https://user-images.githubusercontent.com/3477277/28070375-4060f19e-667f-11e7-9b32-4ede48766bf7.png)

3.堆栈跟踪如下：
![ldb8_8cyy3kws4_baz45fto](https://user-images.githubusercontent.com/3477277/28070388-4a03c406-667f-11e7-8137-9b59ef42d4ef.png)

4.根本原因，是在单机模式时，照样向socketlog推送了日志，导致日志channel爆满。这里应该加个判断是否为client模式
![g xzfhe04ry s2i27bqw0](https://user-images.githubusercontent.com/3477277/28070410-67e460d4-667f-11e7-95eb-7db993849942.png)

![image](https://user-images.githubusercontent.com/3477277/28070426-712dc00e-667f-11e7-824e-2845f6d46ba4.png)

而bl.steal这个chennel是client模式下，client发送给server的channel，在单机模式下没有从chennel获取数据，这个channel只有在client模式下才能被读取到
![lptfbf 1f7_n lmiilf18rs](https://user-images.githubusercontent.com/3477277/28070476-a3d1f584-667f-11e7-9140-3962d81dd7a5.png)

![93g2iybwi uf4 6 y ukxt](https://user-images.githubusercontent.com/3477277/28070486-a8fd970c-667f-11e7-8ae1-7ef1260be79a.png)

![t i5377o g b3ehms_ 4](https://user-images.githubusercontent.com/3477277/28070492-ad933d12-667f-11e7-81ab-566c2d058961.png)

**Comment by andeya** [comment]
感谢你的详尽分析，我马上做跟踪，并解决该问题

**Comment by andeya** [comment]
@lxslove 已经修复，非常感谢你的反馈！！！
https://github.com/henrylee2cn/pholcus/commit/c1d181f5360d136b1c7f6b231a1e7c936a5a2a7f
