### ISSUE TITLE
能否支持增量方式抓取？

### ISSUE THREAD

**Issue by 0xCC0x01** [andeya/pholcus#56]
output都是以StarttTime为目录，这样每次抓取的结果，都保存在不同路径。
是否支持增量方式？在之前结果的基础上，抓取新增内容，保存在同个文件中？

**Comment by andeya** [comment]
输出的文件有时间后缀，不同次执行，时间后缀不同。
但是因为支持记录成功抓取过的url，所以多次执行规则，可以跳过已抓取的url。
至于，同一个url页面中新增内容，则需要自己在规则中进行判断。

**Comment by 0xCC0x01** [comment]
感谢回复，还是有疑问：
比如有页面: p1, p2, p3, ..., p100
如果第一次抓取了P1, P2两个页面, 再次执行规则时，就直接结束了，提示“无采集结果”；
如果将“继承并保存成功记录”设置为“No”，可以抓取，但是会重新从P1开始；
怎么处理，才能使再次执行时，从P3开始抓取呢？
