### ISSUE TITLE
功能建议：分批输出（入库）可新增定时输出（时间判断）

### ISSUE THREAD

**Issue by zerozh** [andeya/pholcus#69]
爬虫可能抓取某些更新频率不高的网站，如一天新增5篇文章，同时设置每10条数据入库一次。
这会导致数据迟迟不能入库则无法后续处理，而设置为每1~5条数据输出会造成较大的数据库压力。

建议：可同时设置 分批输出的 **数量** 和 **时间** 限制，如每达到10条数据或每五分钟可输出一次

**Comment by andeya** [comment]
嗯，按时间输出可以先做成统一全局的
