### ISSUE TITLE
不错的项目，哪里有spider规则文档么？

### ISSUE THREAD

**Issue by sidney9111** [andeya/pholcus#73]
不错的项目，框架也写的杠杠的
但好像一些基本的文档反而是没有，估计大神都不屑吧
求基本spider文档
GetSpiderLib
如何获取默认的spider
 这些默认模板没找到，参考一下也好

看了一些issue，至于规则应用开发，应该是还没调试框架吧

**Comment by andeya** [comment]
GetSpiderLib这个只有在你直接使用app包开发时才有用。否则，使用cmd、gui、web三种操作界面时，是不需要关心这些的。只需要import到规则，然后编译后自动加载。

**Comment by sidney9111** [comment]
动态 html规则是能加上去的，但是例子太少了，只能用GO了
WEB正常显示，
在car_home目录下添加了一个
c ar_home_test.go，也编译通过了
不知道WEB为什么不显示

**Comment by andeya** [comment]
应该是没有import到

**Comment by sidney9111** [comment]
应该是有IMPORT的
package pholcus_lib

import (
	_ "github.com/henrylee2cn/pholcus_lib/photo_home"
	_ "github.com/henrylee2cn/pholcus_lib/IJGUC"
	_ "github.com/henrylee2cn/pholcus_lib/alibaba"

我改了，lib里面的go文件，但是web-》run并没有不同，不知道是什么问题

**Comment by sidney9111** [comment]
即使是我改了，lib里面的go文件，但是web-》run并没有不同，不知道是什么问题

**Comment by sidney9111** [comment]
知道问题了，原来一直用错了根目录BIN目录下面那个EXE
不好意思。。。。。结案吧
要用SRC目录下的。。。。。。
