### ISSUE TITLE
compile error : cannot find package "github.com/henrylee2cn/pholcus_lib/jiban"

### ISSUE THREAD

**Issue by beenchaos** [andeya/pholcus#78]
[root@centos pholcus]# pwd
/root/go/src/github.com/henrylee2cn/pholcus

[root@centos pholcus]# go build
../pholcus_lib/pholcus_lib.go:17:2: cannot find package "github.com/henrylee2cn/pholcus_lib/jiban" in any of:
	/usr/lib/golang/src/github.com/henrylee2cn/pholcus_lib/jiban (from $GOROOT)
	/root/go/src/github.com/henrylee2cn/pholcus_lib/jiban (from $GOPATH)
[root@centos pholcus]# go install
../pholcus_lib/pholcus_lib.go:17:2: cannot find package "github.com/henrylee2cn/pholcus_lib/jiban" in any of:
	/usr/lib/golang/src/github.com/henrylee2cn/pholcus_lib/jiban (from $GOROOT)
	/root/go/src/github.com/henrylee2cn/pholcus_lib/jiban (from $GOPATH)

**Comment by watchpoints** [comment]
pholcus_lib.go  
mv _ "github.com/henrylee2cn/pholcus_lib/jiban"

**Comment by lynic** [comment]
I met the same issue.
