### ISSUE TITLE
cmd模式下定时爬取怎么输出数据

### ISSUE THREAD

**Issue by minusy** [andeya/pholcus#82]
cmd模式下，开启定时爬取，按Ctrl+C直接退出，没有结果输出

**Comment by andeya** [comment]
你加上-h看看参数，你指定了输出方式，就会输出的

**Comment by minusy** [comment]
ctrl+c的时候，pipeline还没dockercap容量还没关闭，没有输出，而ctrl+C会把这个进程终止掉，它还没处理就退出了
