### ISSUE TITLE
能否支持在线编辑和测试爬虫?

### ISSUE THREAD

**Issue by c4ys** [andeya/pholcus#9]
如题.

**Comment by andeya** [comment]
Pholcus有web界面，你指的在线编辑与测试是什么？

**Comment by joln** [comment]
个人理解是新增需要爬取的站点

**Comment by joln** [comment]
需要从spider_lib增加吧

**Comment by andeya** [comment]
其实随便一个位置的规则包，只有导入了，就可以增加上去

**Comment by joln** [comment]
https://pholcus.gitbooks.io/docs/content/index.html 为什么后面很多内容都没有？

**Comment by andeya** [comment]
没时间写，非常抱歉了，有问题直接在【Go 大数据】：http://jq.qq.com/?_wv=1027&k=c75pVF
问我吧
