### ISSUE TITLE
数据插入错位 字段不对应 动态规则 两个规则同时采集 插入一个数据表

### ISSUE THREAD

**Issue by smirkcat** [andeya/pholcus#90]
![w66vd uf 5tb v2f xfmnm](https://user-images.githubusercontent.com/13444394/40643949-41ef567c-6354-11e8-88ba-8d923514d75c.png)

**Comment by smirkcat** [comment]
问题更新 分别采集是没问题（关闭程序重新启动） 但同时采集就有问题了 是不是同事运行时某个地方冲突了 ，

**Comment by andeya** [comment]
两个规则确实不能同时插入同一张表，否则会有数据污染
