### ISSUE TITLE
能否将regexp.Compile("\\<[\\S\\s]+?\\>")换成regexp.Compile("<[^>]+>")

### ISSUE THREAD

**Issue by excosy** [andeya/pholcus#93]
regexp.Compile("\\\\<[\\\\S\\\\s]+?\\\\>")，\S\s是所有的空格和非空格，[]是字符集，包含空格和非空格的字符集不就是所有字符？'<' '>'这俩可以不用转义，那么"\\<[\\S\\s]+?\\>" => "<.+?>" => "<[^>]+>"

**Comment by andeya** [comment]
你指的哪里，可以发一下链接吗？

**Comment by excosy** [comment]
比如github.com/henrylee2cn/pholcus/app/spider/common/common.go，项目里几乎所有查找标签的地方都用了\\\\<[\\\\S\\\\s]+?\\\\>这种写法

**Comment by excosy** [comment]
另外，html规则文件改成xml吧，这玩意也不是html，html的namespace固定了html tag

**Comment by andeya** [comment]
goquery一直是默认的方法啊。
common中提供的是一些通用处理函数，goquery不适合。
改成xml从语法上是更合适，之所以没有选择xml做扩展名，是因为它不支持javascript的高亮与自动格式化。在文件类型与易写两者之间，我选择了易写

**Comment by andeya** [comment]
"\<[\S\s]+?\>" => "<[^>]+>" 你给出的优化确实是更佳的，学习了。

不过<.+?>就不太好了，匹配不到换行符。

最终，我可以接受的是："\\<" => "<"  "\\>" => ">"

**Comment by excosy** [comment]
多行匹配可以用flags：`s := regexp.MustCompile("(?s)<.+?>")`
ref: https://golang.org/pkg/regexp/syntax/
