### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by gerrylon** [andeya/pholcus#96]
您好, 在go get时, 发生错误 希望您能看看:
[root@gl src]# go get -u -v github.com/henrylee2cn/pholcus
github.com/henrylee2cn/pholcus (download)
github.com/henrylee2cn/goutil (download)
github.com/henrylee2cn/pholcus_lib (download)
github.com/tidwall/gjson (download)
github.com/tidwall/match (download)
github.com/henrylee2cn/pholcus/vendor/github.com/Shopify/sarama
# github.com/henrylee2cn/pholcus/vendor/github.com/Shopify/sarama

`github.com/henrylee2cn/pholcus/vendor/github.com/Shopify/sarama/config.go:82:16: undefined: RequiredAcks`
错误在最后一行, 已经标灰了, go版本: go version go1.9.7 linux/amd64

**Comment by andeya** [comment]
应该是文件没下载完就断了吧，重新下载
