### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by speters** [andeya/pholcus#98]
Thank you for this fantastic project,  @henrylee2cn !

It would be great if you would introduce means of **i18n**, so that this fantastic software could be translated without the risk of getting a codebase that diverges from your original (your project already has too many forks which fell behind your development without having contributed any code).

[go-i18n](https://godoc.org/github.com/nicksnyder/go-i18n/i18n) seems to be used most for i18n in Go.

At a glance, there seem to be [~200 strings](https://github.com/henrylee2cn/pholcus/files/2366846/msg.zh.txt) which could be considered for translation.

-----
https://github.com/henrylee2cn/pholcus/issues/80 https://github.com/henrylee2cn/pholcus/issues/77

**Comment by andeya** [comment]
Sorry, I don't have time to schedule an English document, but I agree with it.

> 在 2018年9月10日，下午10:56，Sönke J. Peters <notifications@github.com> 写道：
> 
> #80 <https://github.com/henrylee2cn/pholcus/issues/80>

**Comment by peternavr** [comment]
@henrylee2cn Do you have a list of all the places we'd have to translate?

**Comment by andeya** [comment]
> @henrylee2cn Do you have a list of all the places we'd have to translate?

Mainly the text in these UI, and the README.md
